spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        type: trace
#        format_sql: true
#        use_sql_comments: true
  batch:
    job:
      enabled: false #어플리케이션 구동시 컨텍스트 내의 모든 스프링 배치 작업 자동 실행 여부(false로 해야 구동시 무조건 실행이 안됨)

#logging:
#  level:
#    org:
#      hibernate:
##        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace